# The URL the site will be built for
base_url = "https://ivymect.in"

title = "ivy's site"
description = "Lipsum Ipsum"

default_language = "en"

compile_sass = false
build_search_index = true

[markdown]
highlight_code = false

[extra]
keywords = ["put", "your", "pagewide", "keywords", "here"]
author = "Ivy Pierlot"
